# Generated by Django 4.1.3 on 2022-11-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_body_alter_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=10),
        ),
    ]
